export const sampleData = [
  {
    id: "1",
    name: "4033 NW Yeon Avenue and 3610 & 3620 NW St. Helens Road",
    address: {
      lineOne: "4033 NW Yeon Ave.",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97209",
    },
    email: "4033nwyeonavenue@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: 150680,
    leaseCount: 1,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "2",
    name: "Awesome Suggested Property Name",
    address: {
      lineOne: "5440 SW Westgate Dr.",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97221",
    },
    email: "awesomesuggestedproperty@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: null,
    leaseCount: 1,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "3",
    name: "Completely QAed",
    address: {
      lineOne: "5440 SW Westgate Dr.",
      city: "Portland",
      state: "Washington",
      stateCode: "WA",
      postalCode: "98101",
    },
    email: "completelyqaed@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: null,
    leaseCount: 2,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "4",
    name: "4000Sth",
    address: {
      lineOne: "4000 NW StHelens Rd",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97210",
    },
    email: "4000sth@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: null,
    leaseCount: 1,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "5",
    name: "PCCF",
    address: {
      lineOne: "2225 N. Vancouver Ave.",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97227",
    },
    email: "pccf@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: 13440,
    leaseCount: 11,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "6",
    name: "Highlands at Sylvan Office Building",
    address: {
      lineOne: "5440 SW Westgate Dr.",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97221",
    },
    email: "highlandsatsylvanofficebuild@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: null,
    leaseCount: 1,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "7",
    name: "4200 Northwest Yeon Avenue",
    address: {
      lineOne: "4200 Northwest Yeon Avenue",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97210",
    },
    email: "4200northwestyeonavenue@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: null,
    leaseCount: 1,
    occupancy: 0,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "8",
    name: "The Pine Offices",
    address: {
      lineOne: "12 Pine St",
      city: "Seattle",
      state: "Washington",
      stateCode: "WA",
      postalCode: "98101",
    },
    email: "pineoffices@mail.cardinal.wtf",
    type: "Office",
    leasableArea: 42000,
    leaseCount: 5,
    occupancy: 87,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "9",
    name: "Riverfront Plaza",
    address: {
      lineOne: "99 Riverfront Dr",
      city: "Spokane",
      state: "Washington",
      stateCode: "WA",
      postalCode: "99201",
    },
    email: "riverfrontplaza@mail.cardinal.wtf",
    type: "Retail",
    leasableArea: 18200,
    leaseCount: 9,
    occupancy: 78,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "10",
    name: "Harbor Heights",
    address: {
      lineOne: "800 Harbor Ave",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97205",
    },
    email: "harborheights@mail.cardinal.wtf",
    type: "Mixed-Use",
    leasableArea: 66500,
    leaseCount: 14,
    occupancy: 92,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "11",
    name: "Maple Row",
    address: {
      lineOne: "1400 Maple Row",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      postalCode: "97204",
    },
    email: "maplerow@mail.cardinal.wtf",
    type: "Industrial",
    leasableArea: 32000,
    leaseCount: 3,
    occupancy: 64,
    current: null,
    lastUpdated: "7/31/2025",
  },
  {
    id: "12",
    name: "Juniper Park",
    address: {
      lineOne: "77 Juniper Park",
      city: "Tacoma",
      state: "Washington",
      stateCode: "WA",
      postalCode: "98402",
    },
    email: "juniperpark@mail.cardinal.wtf",
    type: "Office",
    leasableArea: 50800,
    leaseCount: 7,
    occupancy: 71,
    current: null,
    lastUpdated: "7/31/2025",
  },
];
